# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
development:
    user_name: <%= ENV['USER_NAME'] %>
    password: <%= ENV['PASSWORD'] %>
    addres: <%= ENV['ADDRESS'] %>
    domain: <%= ENV['DOMAIN'] %>
    port: <%= ENV['PORT'] %>
    secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  secret_key_base: b166d3dadf688f033c23465d0b02621119e4ee37be9b28f4b5b237655104ec9d31ad4f52fea1a6fe75db9b7260759e17b5f948e10a080dbc2a582566747695fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  user_name: <%= ENV['USER_NAME'] %>
  password: <%= ENV['PASSWORD'] %>
  addres: <%= ENV['ADDRESS'] %>
  domain: <%= ENV['DOMAIN'] %>
  port: <%= ENV['PORT'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
